export const style = {
  TS_Bold: '1',
  TS_Dim: '2',
  TS_Italic: '3',
  TS_Underline: '4',
  TS_Blink_Slow: '5',
  TS_Blink_Fast: '6',
  TS_Reverse: '7',
  TS_Hidden: '8',
  TS_Strikethrough: '9',
  TS_Rare: '20',
  TS_Reset_Bold_2UL: '21',
  TS_Reset_intensity: '22',
  TS_Reset_italic: '23',
  TS_Reset_underlined: '24',
  TS_Reset_blinking: '25',
  TS_Reset_inverted: '27',
  TS_Reset_hidden: '28',
  TS_Reset_struck: '29',
  BG_Normal_Black: '30',
  BG_Normal_Red: '31',
  BG_Normal_Green: '32',
  BG_Normal_Yellow: '33',
  BG_Normal_Blue: '34',
  BG_Normal_Magenta: '35',
  BG_Normal_Cyan: '36',
  BG_Normal_White: '37',
  BG_Bright_Black: '90',
  BG_Bright_Red: '91',
  BG_Bright_Green: '92',
  BG_Bright_Yellow: '93',
  BG_Bright_Blue: '94',
  BG_Bright_Magenta: '95',
  BG_Bright_Cyan: '96',
  BG_Bright_White: '97',
  FG_Normal_Black: '40',
  FG_Normal_Red: '41',
  FG_Normal_Green: '42',
  FG_Normal_Yellow: '43',
  FG_Normal_Blue: '44',
  FG_Normal_Magenta: '45',
  FG_Normal_Cyan: '46',
  FG_Normal_White: '47',
  FG_Bright_Black: '100',
  FG_Bright_Red: '101',
  FG_Bright_Green: '102',
  FG_Bright_Yellow: '103',
  FG_Bright_Blue: '104',
  FG_Bright_Magenta: '105',
  FG_Bright_Cyan: '106',
  FG_Bright_White: '107',
};

export const canvas: {
  config: {
    title: string[],
    text: string[],
    primary: string[],
    secondary: string[],
    tertiary: string[],
    success: string[],
    failed: string[],
    warning: string[],
    taskActive: boolean,
    postActive: boolean,
    tabSpace: number,
  },
  divider: {
    top: string,
    mid: string,
    low: string,
  },

  tab: string,
  width: () => number,
} = {
  config: {
    title: [],
    text: [],
    primary: [],
    secondary: [],
    tertiary: [],
    success: [],
    failed: [],
    warning: [],
    taskActive: true,
    postActive: true,
    tabSpace: 2,
  },

  divider: {
    top: "‾",
    mid: "─",
    low: "_",
  },

  tab: " ",
  width: () => typeof process.stdout.columns === 'number' ? process.stdout.columns : 48
};

Object.assign(canvas.config,
  {
    title: [style.BG_Normal_Green],
    text: [style.BG_Normal_White],
    primary: [style.BG_Normal_Yellow],
    secondary: [style.BG_Bright_Yellow],
    tertiary: [style.BG_Bright_Black],
    success: [style.BG_Normal_Green],
    failed: [style.BG_Normal_Red],
    warning: [style.BG_Normal_Yellow],
  }
);

export function format(string = '', ...styles: (typeof style)[keyof typeof style][]) {
  return `\x1b[${styles.join(';')}m${string}\x1b[0m`;
}