package shell

type t_ColorsAnsiFunc map[int]func(string) string

// Syntax: Style.{Appearence}[Canvas.Color.{***}]("{***}")   
var Style = struct{
		Shade                    t_ColorsAnsiFunc
		Text                     t_ColorsAnsiFunc
		Bold                     t_ColorsAnsiFunc
		Dim                      t_ColorsAnsiFunc
		Italic                   t_ColorsAnsiFunc
		Uline                    t_ColorsAnsiFunc
		Invert                   t_ColorsAnsiFunc
		BoldDim                  t_ColorsAnsiFunc
		BoldInvert               t_ColorsAnsiFunc
		BoldItalic               t_ColorsAnsiFunc
		BoldUline                t_ColorsAnsiFunc
		DimInvert                t_ColorsAnsiFunc
		DimItalic                t_ColorsAnsiFunc
		DimUline                 t_ColorsAnsiFunc
		InvertItalic             t_ColorsAnsiFunc
		InvertUline              t_ColorsAnsiFunc
		ItalicUline              t_ColorsAnsiFunc
		BoldItalicUline          t_ColorsAnsiFunc
		BoldDimItalic            t_ColorsAnsiFunc
		BoldDimUline             t_ColorsAnsiFunc
		DimItalicUline           t_ColorsAnsiFunc
		BoldDimInvert            t_ColorsAnsiFunc
		BoldInvertItalic         t_ColorsAnsiFunc
		BoldInvertUline          t_ColorsAnsiFunc
		DimInvertItalic          t_ColorsAnsiFunc
		DimInvertUline           t_ColorsAnsiFunc
		InvertItalicUline        t_ColorsAnsiFunc
		BoldDimInvertItalic      t_ColorsAnsiFunc
		BoldDimInvertUline       t_ColorsAnsiFunc
		BoldDimItalicUline       t_ColorsAnsiFunc
		BoldInvertItalicUline    t_ColorsAnsiFunc
		DimInvertItalicUline     t_ColorsAnsiFunc
		BoldDimInvertItalicUline t_ColorsAnsiFunc
}{
	Shade: t_ColorsAnsiFunc{
		Canvas.Color.Red:     func(text string) string { return "\x1b[0m\x1b[41m" + text },
		Canvas.Color.Orange:  func(text string) string { return "\x1b[0m\x1b[48;5;214m" + text },
		Canvas.Color.Yellow:  func(text string) string { return "\x1b[0m\x1b[43m" + text },
		Canvas.Color.Green:   func(text string) string { return "\x1b[0m\x1b[42m" + text },
		Canvas.Color.Cyan:    func(text string) string { return "\x1b[0m\x1b[46m" + text },
		Canvas.Color.Blue:    func(text string) string { return "\x1b[0m\x1b[44m" + text },
		Canvas.Color.Purple:  func(text string) string { return "\x1b[0m\x1b[48;5;93m" + text },
		Canvas.Color.Magenta: func(text string) string { return "\x1b[0m\x1b[45m" + text },
		Canvas.Color.Pink:    func(text string) string { return "\x1b[0m\x1b[48;5;205m" + text },
		Canvas.Color.Grey:    func(text string) string { return "\x1b[0m\x1b[48;5;240m" + text },
		Canvas.Color.White:   func(text string) string { return "\x1b[0m\x1b[47m" + text },
	},
	Text: t_ColorsAnsiFunc{
		Canvas.Color.Red:     func(text string) string { return "\x1b[0m\x1b[31m" + text },
		Canvas.Color.Orange:  func(text string) string { return "\x1b[0m\x1b[38;5;214m" + text },
		Canvas.Color.Yellow:  func(text string) string { return "\x1b[0m\x1b[33m" + text },
		Canvas.Color.Green:   func(text string) string { return "\x1b[0m\x1b[32m" + text },
		Canvas.Color.Cyan:    func(text string) string { return "\x1b[0m\x1b[36m" + text },
		Canvas.Color.Blue:    func(text string) string { return "\x1b[0m\x1b[34m" + text },
		Canvas.Color.Purple:  func(text string) string { return "\x1b[0m\x1b[38;5;93m" + text },
		Canvas.Color.Magenta: func(text string) string { return "\x1b[0m\x1b[35m" + text },
		Canvas.Color.Pink:    func(text string) string { return "\x1b[0m\x1b[38;5;205m" + text },
		Canvas.Color.Grey:    func(text string) string { return "\x1b[0m\x1b[38;5;240m" + text },
		Canvas.Color.White:   func(text string) string { return "\x1b[0m\x1b[37m" + text },
	},

	Bold: t_ColorsAnsiFunc{
		Canvas.Color.Red:     func(text string) string { return "\x1b[0m\x1b[1;31m" + text },
		Canvas.Color.Orange:  func(text string) string { return "\x1b[0m\x1b[1;38;5;214m" + text },
		Canvas.Color.Yellow:  func(text string) string { return "\x1b[0m\x1b[1;33m" + text },
		Canvas.Color.Green:   func(text string) string { return "\x1b[0m\x1b[1;32m" + text },
		Canvas.Color.Cyan:    func(text string) string { return "\x1b[0m\x1b[1;36m" + text },
		Canvas.Color.Blue:    func(text string) string { return "\x1b[0m\x1b[1;34m" + text },
		Canvas.Color.Purple:  func(text string) string { return "\x1b[0m\x1b[1;38;5;93m" + text },
		Canvas.Color.Magenta: func(text string) string { return "\x1b[0m\x1b[1;35m" + text },
		Canvas.Color.Pink:    func(text string) string { return "\x1b[0m\x1b[1;38;5;205m" + text },
		Canvas.Color.Grey:    func(text string) string { return "\x1b[0m\x1b[1;38;5;240m" + text },
		Canvas.Color.White:   func(text string) string { return "\x1b[0m\x1b[1;37m" + text },
	},
	Dim: t_ColorsAnsiFunc{
		Canvas.Color.Red:     func(text string) string { return "\x1b[0m\x1b[2;31m" + text },
		Canvas.Color.Orange:  func(text string) string { return "\x1b[0m\x1b[2;38;5;214m" + text },
		Canvas.Color.Yellow:  func(text string) string { return "\x1b[0m\x1b[2;33m" + text },
		Canvas.Color.Green:   func(text string) string { return "\x1b[0m\x1b[2;32m" + text },
		Canvas.Color.Cyan:    func(text string) string { return "\x1b[0m\x1b[2;36m" + text },
		Canvas.Color.Blue:    func(text string) string { return "\x1b[0m\x1b[2;34m" + text },
		Canvas.Color.Purple:  func(text string) string { return "\x1b[0m\x1b[2;38;5;93m" + text },
		Canvas.Color.Magenta: func(text string) string { return "\x1b[0m\x1b[2;35m" + text },
		Canvas.Color.Pink:    func(text string) string { return "\x1b[0m\x1b[2;38;5;205m" + text },
		Canvas.Color.Grey:    func(text string) string { return "\x1b[0m\x1b[2;38;5;240m" + text },
		Canvas.Color.White:   func(text string) string { return "\x1b[0m\x1b[2;37m" + text },
	},
	Italic: t_ColorsAnsiFunc{
		Canvas.Color.Red:     func(text string) string { return "\x1b[0m\x1b[3;31m" + text },
		Canvas.Color.Orange:  func(text string) string { return "\x1b[0m\x1b[3;38;5;214m" + text },
		Canvas.Color.Yellow:  func(text string) string { return "\x1b[0m\x1b[3;33m" + text },
		Canvas.Color.Green:   func(text string) string { return "\x1b[0m\x1b[3;32m" + text },
		Canvas.Color.Cyan:    func(text string) string { return "\x1b[0m\x1b[3;36m" + text },
		Canvas.Color.Blue:    func(text string) string { return "\x1b[0m\x1b[3;34m" + text },
		Canvas.Color.Purple:  func(text string) string { return "\x1b[0m\x1b[3;38;5;93m" + text },
		Canvas.Color.Magenta: func(text string) string { return "\x1b[0m\x1b[3;35m" + text },
		Canvas.Color.Pink:    func(text string) string { return "\x1b[0m\x1b[3;38;5;205m" + text },
		Canvas.Color.Grey:    func(text string) string { return "\x1b[0m\x1b[3;38;5;240m" + text },
		Canvas.Color.White:   func(text string) string { return "\x1b[0m\x1b[3;37m" + text },
	},
	Uline: t_ColorsAnsiFunc{
		Canvas.Color.Red:     func(text string) string { return "\x1b[0m\x1b[4;31m" + text },
		Canvas.Color.Orange:  func(text string) string { return "\x1b[0m\x1b[4;38;5;214m" + text },
		Canvas.Color.Yellow:  func(text string) string { return "\x1b[0m\x1b[4;33m" + text },
		Canvas.Color.Green:   func(text string) string { return "\x1b[0m\x1b[4;32m" + text },
		Canvas.Color.Cyan:    func(text string) string { return "\x1b[0m\x1b[4;36m" + text },
		Canvas.Color.Blue:    func(text string) string { return "\x1b[0m\x1b[4;34m" + text },
		Canvas.Color.Purple:  func(text string) string { return "\x1b[0m\x1b[4;38;5;93m" + text },
		Canvas.Color.Magenta: func(text string) string { return "\x1b[0m\x1b[4;35m" + text },
		Canvas.Color.Pink:    func(text string) string { return "\x1b[0m\x1b[4;38;5;205m" + text },
		Canvas.Color.Grey:    func(text string) string { return "\x1b[0m\x1b[4;38;5;240m" + text },
		Canvas.Color.White:   func(text string) string { return "\x1b[0m\x1b[4;37m" + text },
	},
	Invert: t_ColorsAnsiFunc{
		Canvas.Color.Red:     func(text string) string { return "\x1b[0m\x1b[31m\x1b[7m" + text },
		Canvas.Color.Orange:  func(text string) string { return "\x1b[0m\x1b[38;5;214m\x1b[7m" + text },
		Canvas.Color.Yellow:  func(text string) string { return "\x1b[0m\x1b[33m\x1b[7m" + text },
		Canvas.Color.Green:   func(text string) string { return "\x1b[0m\x1b[32m\x1b[7m" + text },
		Canvas.Color.Cyan:    func(text string) string { return "\x1b[0m\x1b[36m\x1b[7m" + text },
		Canvas.Color.Blue:    func(text string) string { return "\x1b[0m\x1b[34m\x1b[7m" + text },
		Canvas.Color.Purple:  func(text string) string { return "\x1b[0m\x1b[38;5;93m\x1b[7m" + text },
		Canvas.Color.Magenta: func(text string) string { return "\x1b[0m\x1b[35m\x1b[7m" + text },
		Canvas.Color.Pink:    func(text string) string { return "\x1b[0m\x1b[38;5;205m\x1b[7m" + text },
		Canvas.Color.Grey:    func(text string) string { return "\x1b[0m\x1b[38;5;240m\x1b[7m" + text },
		Canvas.Color.White:   func(text string) string { return "\x1b[0m\x1b[37m\x1b[7m" + text },
	},

	BoldDim: t_ColorsAnsiFunc{
		Canvas.Color.Red:     func(text string) string { return "\x1b[0m\x1b[1;2;31m" + text },
		Canvas.Color.Orange:  func(text string) string { return "\x1b[0m\x1b[1;2;38;5;214m" + text },
		Canvas.Color.Yellow:  func(text string) string { return "\x1b[0m\x1b[1;2;33m" + text },
		Canvas.Color.Green:   func(text string) string { return "\x1b[0m\x1b[1;2;32m" + text },
		Canvas.Color.Cyan:    func(text string) string { return "\x1b[0m\x1b[1;2;36m" + text },
		Canvas.Color.Blue:    func(text string) string { return "\x1b[0m\x1b[1;2;34m" + text },
		Canvas.Color.Purple:  func(text string) string { return "\x1b[0m\x1b[1;2;38;5;93m" + text },
		Canvas.Color.Magenta: func(text string) string { return "\x1b[0m\x1b[1;2;35m" + text },
		Canvas.Color.Pink:    func(text string) string { return "\x1b[0m\x1b[1;2;38;5;205m" + text },
		Canvas.Color.Grey:    func(text string) string { return "\x1b[0m\x1b[1;2;38;5;240m" + text },
		Canvas.Color.White:   func(text string) string { return "\x1b[0m\x1b[1;2;37m" + text },
	},
	BoldInvert: t_ColorsAnsiFunc{
		Canvas.Color.Red:     func(text string) string { return "\x1b[0m\x1b[1;31;7m" + text },
		Canvas.Color.Orange:  func(text string) string { return "\x1b[0m\x1b[1;38;5;214;7m" + text },
		Canvas.Color.Yellow:  func(text string) string { return "\x1b[0m\x1b[1;33;7m" + text },
		Canvas.Color.Green:   func(text string) string { return "\x1b[0m\x1b[1;32;7m" + text },
		Canvas.Color.Cyan:    func(text string) string { return "\x1b[0m\x1b[1;36;7m" + text },
		Canvas.Color.Blue:    func(text string) string { return "\x1b[0m\x1b[1;34;7m" + text },
		Canvas.Color.Purple:  func(text string) string { return "\x1b[0m\x1b[1;38;5;93;7m" + text },
		Canvas.Color.Magenta: func(text string) string { return "\x1b[0m\x1b[1;35;7m" + text },
		Canvas.Color.Pink:    func(text string) string { return "\x1b[0m\x1b[1;38;5;205;7m" + text },
		Canvas.Color.Grey:    func(text string) string { return "\x1b[0m\x1b[1;38;5;240;7m" + text },
		Canvas.Color.White:   func(text string) string { return "\x1b[0m\x1b[1;37;7m" + text },
	},
	BoldItalic: t_ColorsAnsiFunc{
		Canvas.Color.Red:     func(text string) string { return "\x1b[0m\x1b[1;3;31m" + text },
		Canvas.Color.Orange:  func(text string) string { return "\x1b[0m\x1b[1;3;38;5;214m" + text },
		Canvas.Color.Yellow:  func(text string) string { return "\x1b[0m\x1b[1;3;33m" + text },
		Canvas.Color.Green:   func(text string) string { return "\x1b[0m\x1b[1;3;32m" + text },
		Canvas.Color.Cyan:    func(text string) string { return "\x1b[0m\x1b[1;3;36m" + text },
		Canvas.Color.Blue:    func(text string) string { return "\x1b[0m\x1b[1;3;34m" + text },
		Canvas.Color.Purple:  func(text string) string { return "\x1b[0m\x1b[1;3;38;5;93m" + text },
		Canvas.Color.Magenta: func(text string) string { return "\x1b[0m\x1b[1;3;35m" + text },
		Canvas.Color.Pink:    func(text string) string { return "\x1b[0m\x1b[1;3;38;5;205m" + text },
		Canvas.Color.Grey:    func(text string) string { return "\x1b[0m\x1b[1;3;38;5;240m" + text },
		Canvas.Color.White:   func(text string) string { return "\x1b[0m\x1b[1;3;37m" + text },
	},
	BoldUline: t_ColorsAnsiFunc{
		Canvas.Color.Red:     func(text string) string { return "\x1b[0m\x1b[4;1;31m" + text },
		Canvas.Color.Orange:  func(text string) string { return "\x1b[0m\x1b[4;1;38;5;214m" + text },
		Canvas.Color.Yellow:  func(text string) string { return "\x1b[0m\x1b[4;1;33m" + text },
		Canvas.Color.Green:   func(text string) string { return "\x1b[0m\x1b[4;1;32m" + text },
		Canvas.Color.Cyan:    func(text string) string { return "\x1b[0m\x1b[4;1;36m" + text },
		Canvas.Color.Blue:    func(text string) string { return "\x1b[0m\x1b[4;1;34m" + text },
		Canvas.Color.Purple:  func(text string) string { return "\x1b[0m\x1b[4;1;38;5;93m" + text },
		Canvas.Color.Magenta: func(text string) string { return "\x1b[0m\x1b[4;1;35m" + text },
		Canvas.Color.Pink:    func(text string) string { return "\x1b[0m\x1b[4;1;38;5;205m" + text },
		Canvas.Color.Grey:    func(text string) string { return "\x1b[0m\x1b[4;1;38;5;240m" + text },
		Canvas.Color.White:   func(text string) string { return "\x1b[0m\x1b[4;1;37m" + text },
	},
	DimInvert: t_ColorsAnsiFunc{
		Canvas.Color.Red:     func(text string) string { return "\x1b[0m\x1b[2;31;7m" + text },
		Canvas.Color.Orange:  func(text string) string { return "\x1b[0m\x1b[2;38;5;214;7m" + text },
		Canvas.Color.Yellow:  func(text string) string { return "\x1b[0m\x1b[2;33;7m" + text },
		Canvas.Color.Green:   func(text string) string { return "\x1b[0m\x1b[2;32;7m" + text },
		Canvas.Color.Cyan:    func(text string) string { return "\x1b[0m\x1b[2;36;7m" + text },
		Canvas.Color.Blue:    func(text string) string { return "\x1b[0m\x1b[2;34;7m" + text },
		Canvas.Color.Purple:  func(text string) string { return "\x1b[0m\x1b[2;38;5;93;7m" + text },
		Canvas.Color.Magenta: func(text string) string { return "\x1b[0m\x1b[2;35;7m" + text },
		Canvas.Color.Pink:    func(text string) string { return "\x1b[0m\x1b[2;38;5;205;7m" + text },
		Canvas.Color.Grey:    func(text string) string { return "\x1b[0m\x1b[2;38;5;240;7m" + text },
		Canvas.Color.White:   func(text string) string { return "\x1b[0m\x1b[2;37;7m" + text },
	},
	DimItalic: t_ColorsAnsiFunc{
		Canvas.Color.Red:     func(text string) string { return "\x1b[0m\x1b[2;3;31m" + text },
		Canvas.Color.Orange:  func(text string) string { return "\x1b[0m\x1b[2;3;38;5;214m" + text },
		Canvas.Color.Yellow:  func(text string) string { return "\x1b[0m\x1b[2;3;33m" + text },
		Canvas.Color.Green:   func(text string) string { return "\x1b[0m\x1b[2;3;32m" + text },
		Canvas.Color.Cyan:    func(text string) string { return "\x1b[0m\x1b[2;3;36m" + text },
		Canvas.Color.Blue:    func(text string) string { return "\x1b[0m\x1b[2;3;34m" + text },
		Canvas.Color.Purple:  func(text string) string { return "\x1b[0m\x1b[2;3;38;5;93m" + text },
		Canvas.Color.Magenta: func(text string) string { return "\x1b[0m\x1b[2;3;35m" + text },
		Canvas.Color.Pink:    func(text string) string { return "\x1b[0m\x1b[2;3;38;5;205m" + text },
		Canvas.Color.Grey:    func(text string) string { return "\x1b[0m\x1b[2;3;38;5;240m" + text },
		Canvas.Color.White:   func(text string) string { return "\x1b[0m\x1b[2;3;37m" + text },
	},
	DimUline: t_ColorsAnsiFunc{
		Canvas.Color.Red:     func(text string) string { return "\x1b[0m\x1b[2;4;31m" + text },
		Canvas.Color.Orange:  func(text string) string { return "\x1b[0m\x1b[2;4;38;5;214m" + text },
		Canvas.Color.Yellow:  func(text string) string { return "\x1b[0m\x1b[2;4;33m" + text },
		Canvas.Color.Green:   func(text string) string { return "\x1b[0m\x1b[2;4;32m" + text },
		Canvas.Color.Cyan:    func(text string) string { return "\x1b[0m\x1b[2;4;36m" + text },
		Canvas.Color.Blue:    func(text string) string { return "\x1b[0m\x1b[2;4;34m" + text },
		Canvas.Color.Purple:  func(text string) string { return "\x1b[0m\x1b[2;4;38;5;93m" + text },
		Canvas.Color.Magenta: func(text string) string { return "\x1b[0m\x1b[2;4;35m" + text },
		Canvas.Color.Pink:    func(text string) string { return "\x1b[0m\x1b[2;4;38;5;205m" + text },
		Canvas.Color.Grey:    func(text string) string { return "\x1b[0m\x1b[2;4;38;5;240m" + text },
		Canvas.Color.White:   func(text string) string { return "\x1b[0m\x1b[2;4;37m" + text },
	},
	InvertItalic: t_ColorsAnsiFunc{
		Canvas.Color.Red:     func(text string) string { return "\x1b[0m\x1b[3;31;7m" + text },
		Canvas.Color.Orange:  func(text string) string { return "\x1b[0m\x1b[3;38;5;214;7m" + text },
		Canvas.Color.Yellow:  func(text string) string { return "\x1b[0m\x1b[3;33;7m" + text },
		Canvas.Color.Green:   func(text string) string { return "\x1b[0m\x1b[3;32;7m" + text },
		Canvas.Color.Cyan:    func(text string) string { return "\x1b[0m\x1b[3;36;7m" + text },
		Canvas.Color.Blue:    func(text string) string { return "\x1b[0m\x1b[3;34;7m" + text },
		Canvas.Color.Purple:  func(text string) string { return "\x1b[0m\x1b[3;38;5;93m\x1b[7m" + text },
		Canvas.Color.Magenta: func(text string) string { return "\x1b[0m\x1b[3;35m\x1b[7m" + text },
		Canvas.Color.Pink:    func(text string) string { return "\x1b[0m\x1b[38;5;205m\x1b[7m" + text },
		Canvas.Color.Grey:    func(text string) string { return "\x1b[0m\x1b[38;5;240m\x1b[7m" + text },
		Canvas.Color.White:   func(text string) string { return "\x1b[0m\x1b[37m\x1b[7m" + text },
	},
	InvertUline: t_ColorsAnsiFunc{
		Canvas.Color.Red:     func(text string) string { return "\x1b[0m\x1b[4;31;7m" + text },
		Canvas.Color.Orange:  func(text string) string { return "\x1b[0m\x1b[4;38;5;214;7m" + text },
		Canvas.Color.Yellow:  func(text string) string { return "\x1b[0m\x1b[4;33;7m" + text },
		Canvas.Color.Green:   func(text string) string { return "\x1b[0m\x1b[4;32;7m" + text },
		Canvas.Color.Cyan:    func(text string) string { return "\x1b[0m\x1b[4;36;7m" + text },
		Canvas.Color.Blue:    func(text string) string { return "\x1b[0m\x1b[4;34;7m" + text },
		Canvas.Color.Purple:  func(text string) string { return "\x1b[0m\x1b[4;38;5;93m\x1b[7m" + text },
		Canvas.Color.Magenta: func(text string) string { return "\x1b[0m\x1b[4;35m\x1b[7m" + text },
		Canvas.Color.Pink:    func(text string) string { return "\x1b[0m\x1b[48;5;205m\x1b[7m" + text },
		Canvas.Color.Grey:    func(text string) string { return "\x1b[0m\x1b[48;5;240m\x1b[7m" + text },
		Canvas.Color.White:   func(text string) string { return "\x1b[0m\x1b[47m\x1b[7m" + text },
	},
	ItalicUline: t_ColorsAnsiFunc{
		Canvas.Color.Red:     func(text string) string { return "\x1b[0m\x1b[4;3;31m" + text },
		Canvas.Color.Orange:  func(text string) string { return "\x1b[0m\x1b[4;3;38;5;214m" + text },
		Canvas.Color.Yellow:  func(text string) string { return "\x1b[0m\x1b[4;3;33m" + text },
		Canvas.Color.Green:   func(text string) string { return "\x1b[0m\x1b[4;3;32m" + text },
		Canvas.Color.Cyan:    func(text string) string { return "\x1b[0m\x1b[4;3;36m" + text },
		Canvas.Color.Blue:    func(text string) string { return "\x1b[0m\x1b[4;3;34m" + text },
		Canvas.Color.Purple:  func(text string) string { return "\x1b[0m\x1b[4;3;38;5;93m" + text },
		Canvas.Color.Magenta: func(text string) string { return "\x1b[0m\x1b[4;3;35m" + text },
		Canvas.Color.Pink:    func(text string) string { return "\x1b[0m\x1b[4;3;38;5;205m" + text },
		Canvas.Color.Grey:    func(text string) string { return "\x1b[0m\x1b[4;3;38;5;240m" + text },
		Canvas.Color.White:   func(text string) string { return "\x1b[0m\x1b[4;3;37m" + text },
	},

	BoldDimItalic: t_ColorsAnsiFunc{
		Canvas.Color.Red:     func(text string) string { return "\x1b[0m\x1b[1;2;3;31m" + text },
		Canvas.Color.Orange:  func(text string) string { return "\x1b[0m\x1b[1;2;3;38;5;214m" + text },
		Canvas.Color.Yellow:  func(text string) string { return "\x1b[0m\x1b[1;2;3;33m" + text },
		Canvas.Color.Green:   func(text string) string { return "\x1b[0m\x1b[1;2;3;32m" + text },
		Canvas.Color.Cyan:    func(text string) string { return "\x1b[0m\x1b[1;2;3;36m" + text },
		Canvas.Color.Blue:    func(text string) string { return "\x1b[0m\x1b[1;2;3;34m" + text },
		Canvas.Color.Purple:  func(text string) string { return "\x1b[0m\x1b[1;2;3;38;5;93m" + text },
		Canvas.Color.Magenta: func(text string) string { return "\x1b[0m\x1b[1;2;3;35m" + text },
		Canvas.Color.Pink:    func(text string) string { return "\x1b[0m\x1b[1;2;3;38;5;205m" + text },
		Canvas.Color.Grey:    func(text string) string { return "\x1b[0m\x1b[1;2;3;38;5;240m" + text },
		Canvas.Color.White:   func(text string) string { return "\x1b[0m\x1b[1;2;3;37m" + text },
	},
	BoldDimUline: t_ColorsAnsiFunc{
		Canvas.Color.Red:     func(text string) string { return "\x1b[0m\x1b[1;2;4;31m" + text },
		Canvas.Color.Orange:  func(text string) string { return "\x1b[0m\x1b[1;2;4;38;5;214m" + text },
		Canvas.Color.Yellow:  func(text string) string { return "\x1b[0m\x1b[1;2;4;33m" + text },
		Canvas.Color.Green:   func(text string) string { return "\x1b[0m\x1b[1;2;4;32m" + text },
		Canvas.Color.Cyan:    func(text string) string { return "\x1b[0m\x1b[1;2;4;36m" + text },
		Canvas.Color.Blue:    func(text string) string { return "\x1b[0m\x1b[1;2;4;34m" + text },
		Canvas.Color.Purple:  func(text string) string { return "\x1b[0m\x1b[1;2;4;38;5;93m" + text },
		Canvas.Color.Magenta: func(text string) string { return "\x1b[0m\x1b[1;2;4;35m" + text },
		Canvas.Color.Pink:    func(text string) string { return "\x1b[0m\x1b[1;2;4;38;5;205m" + text },
		Canvas.Color.Grey:    func(text string) string { return "\x1b[0m\x1b[1;2;4;38;5;240m" + text },
		Canvas.Color.White:   func(text string) string { return "\x1b[0m\x1b[1;2;4;37m" + text },
	},
	BoldDimInvert: t_ColorsAnsiFunc{
		Canvas.Color.Orange:  func(text string) string { return "\x1b[0m\x1b[1;2;7;38;5;214m" + text },
		Canvas.Color.Red:     func(text string) string { return "\x1b[0m\x1b[1;2;7;31m" + text },
		Canvas.Color.Yellow:  func(text string) string { return "\x1b[0m\x1b[1;2;7;33m" + text },
		Canvas.Color.Green:   func(text string) string { return "\x1b[0m\x1b[1;2;7;32m" + text },
		Canvas.Color.Cyan:    func(text string) string { return "\x1b[0m\x1b[1;2;7;36m" + text },
		Canvas.Color.Blue:    func(text string) string { return "\x1b[0m\x1b[1;2;7;34m" + text },
		Canvas.Color.Purple:  func(text string) string { return "\x1b[0m\x1b[1;2;7;38;5;93m" + text },
		Canvas.Color.Magenta: func(text string) string { return "\x1b[0m\x1b[1;2;7;35m" + text },
		Canvas.Color.Pink:    func(text string) string { return "\x1b[0m\x1b[1;2;7;38;5;205m" + text },
		Canvas.Color.Grey:    func(text string) string { return "\x1b[0m\x1b[1;2;7;38;5;240m" + text },
		Canvas.Color.White:   func(text string) string { return "\x1b[0m\x1b[1;2;7;37m" + text },
	},
	BoldInvertItalic: t_ColorsAnsiFunc{
		Canvas.Color.Red:     func(text string) string { return "\x1b[0m\x1b[1;3;7;31m" + text },
		Canvas.Color.Orange:  func(text string) string { return "\x1b[0m\x1b[1;3;7;38;5;214m" + text },
		Canvas.Color.Yellow:  func(text string) string { return "\x1b[0m\x1b[1;3;7;33m" + text },
		Canvas.Color.Green:   func(text string) string { return "\x1b[0m\x1b[1;3;7;32m" + text },
		Canvas.Color.Cyan:    func(text string) string { return "\x1b[0m\x1b[1;3;7;36m" + text },
		Canvas.Color.Blue:    func(text string) string { return "\x1b[0m\x1b[1;3;7;34m" + text },
		Canvas.Color.Purple:  func(text string) string { return "\x1b[0m\x1b[1;3;7;38;5;93m" + text },
		Canvas.Color.Magenta: func(text string) string { return "\x1b[0m\x1b[1;3;7;35m" + text },
		Canvas.Color.Pink:    func(text string) string { return "\x1b[0m\x1b[1;3;7;38;5;205m" + text },
		Canvas.Color.Grey:    func(text string) string { return "\x1b[0m\x1b[1;3;7;38;5;240m" + text },
		Canvas.Color.White:   func(text string) string { return "\x1b[0m\x1b[1;3;7;37m" + text },
	},
	BoldInvertUline: t_ColorsAnsiFunc{
		Canvas.Color.Red:     func(text string) string { return "\x1b[0m\x1b[4;1;7;31m" + text },
		Canvas.Color.Orange:  func(text string) string { return "\x1b[0m\x1b[4;1;7;38;5;214m" + text },
		Canvas.Color.Yellow:  func(text string) string { return "\x1b[0m\x1b[4;1;7;33m" + text },
		Canvas.Color.Green:   func(text string) string { return "\x1b[0m\x1b[4;1;7;32m" + text },
		Canvas.Color.Cyan:    func(text string) string { return "\x1b[0m\x1b[4;1;7;36m" + text },
		Canvas.Color.Blue:    func(text string) string { return "\x1b[0m\x1b[4;1;7;34m" + text },
		Canvas.Color.Purple:  func(text string) string { return "\x1b[0m\x1b[4;1;7;38;5;93m" + text },
		Canvas.Color.Magenta: func(text string) string { return "\x1b[0m\x1b[4;1;7;35m" + text },
		Canvas.Color.Pink:    func(text string) string { return "\x1b[0m\x1b[4;1;7;38;5;205m" + text },
		Canvas.Color.Grey:    func(text string) string { return "\x1b[0m\x1b[4;1;7;38;5;240m" + text },
		Canvas.Color.White:   func(text string) string { return "\x1b[0m\x1b[4;1;7;37m" + text },
	},
	BoldItalicUline: t_ColorsAnsiFunc{
		Canvas.Color.Red:     func(text string) string { return "\x1b[0m\x1b[1;3;4;31m" + text },
		Canvas.Color.Orange:  func(text string) string { return "\x1b[0m\x1b[1;3;4;38;5;214m" + text },
		Canvas.Color.Yellow:  func(text string) string { return "\x1b[0m\x1b[1;3;4;33m" + text },
		Canvas.Color.Green:   func(text string) string { return "\x1b[0m\x1b[1;3;4;32m" + text },
		Canvas.Color.Cyan:    func(text string) string { return "\x1b[0m\x1b[1;3;4;36m" + text },
		Canvas.Color.Blue:    func(text string) string { return "\x1b[0m\x1b[1;3;4;34m" + text },
		Canvas.Color.Purple:  func(text string) string { return "\x1b[0m\x1b[1;3;4;38;5;93m" + text },
		Canvas.Color.Magenta: func(text string) string { return "\x1b[0m\x1b[1;3;4;35m" + text },
		Canvas.Color.Pink:    func(text string) string { return "\x1b[0m\x1b[1;3;4;38;5;205m" + text },
		Canvas.Color.Grey:    func(text string) string { return "\x1b[0m\x1b[1;3;4;38;5;240m" + text },
		Canvas.Color.White:   func(text string) string { return "\x1b[0m\x1b[1;3;4;37m" + text },
	},
	DimInvertItalic: t_ColorsAnsiFunc{
		Canvas.Color.Red:     func(text string) string { return "\x1b[0m\x1b[2;3;7;31m" + text },
		Canvas.Color.Orange:  func(text string) string { return "\x1b[0m\x1b[2;3;7;38;5;214m" + text },
		Canvas.Color.Yellow:  func(text string) string { return "\x1b[0m\x1b[2;3;7;33m" + text },
		Canvas.Color.Green:   func(text string) string { return "\x1b[0m\x1b[2;3;7;32m" + text },
		Canvas.Color.Cyan:    func(text string) string { return "\x1b[0m\x1b[2;3;7;36m" + text },
		Canvas.Color.Blue:    func(text string) string { return "\x1b[0m\x1b[2;3;7;34m" + text },
		Canvas.Color.Purple:  func(text string) string { return "\x1b[0m\x1b[2;3;7;38;5;93m" + text },
		Canvas.Color.Magenta: func(text string) string { return "\x1b[0m\x1b[2;3;7;35m" + text },
		Canvas.Color.Pink:    func(text string) string { return "\x1b[0m\x1b[2;3;7;38;5;205m" + text },
		Canvas.Color.Grey:    func(text string) string { return "\x1b[0m\x1b[2;3;7;38;5;240m" + text },
		Canvas.Color.White:   func(text string) string { return "\x1b[0m\x1b[2;3;7;37m" + text },
	},
	DimInvertUline: t_ColorsAnsiFunc{
		Canvas.Color.Red:     func(text string) string { return "\x1b[0m\x1b[2;4;7;31m" + text },
		Canvas.Color.Orange:  func(text string) string { return "\x1b[0m\x1b[2;4;7;38;5;214m" + text },
		Canvas.Color.Yellow:  func(text string) string { return "\x1b[0m\x1b[2;4;7;33m" + text },
		Canvas.Color.Green:   func(text string) string { return "\x1b[0m\x1b[2;4;7;32m" + text },
		Canvas.Color.Cyan:    func(text string) string { return "\x1b[0m\x1b[2;4;7;36m" + text },
		Canvas.Color.Blue:    func(text string) string { return "\x1b[0m\x1b[2;4;7;34m" + text },
		Canvas.Color.Purple:  func(text string) string { return "\x1b[0m\x1b[2;4;7;38;5;93m" + text },
		Canvas.Color.Magenta: func(text string) string { return "\x1b[0m\x1b[2;4;7;35m" + text },
		Canvas.Color.Pink:    func(text string) string { return "\x1b[0m\x1b[2;4;7;38;5;205m" + text },
		Canvas.Color.Grey:    func(text string) string { return "\x1b[0m\x1b[2;4;7;38;5;240m" + text },
		Canvas.Color.White:   func(text string) string { return "\x1b[0m\x1b[2;4;7;37m" + text },
	},
	DimItalicUline: t_ColorsAnsiFunc{
		Canvas.Color.Red:     func(text string) string { return "\x1b[0m\x1b[2;3;4;31m" + text },
		Canvas.Color.Orange:  func(text string) string { return "\x1b[0m\x1b[2;3;4;38;5;214m" + text },
		Canvas.Color.Yellow:  func(text string) string { return "\x1b[0m\x1b[2;3;4;33m" + text },
		Canvas.Color.Green:   func(text string) string { return "\x1b[0m\x1b[2;3;4;32m" + text },
		Canvas.Color.Cyan:    func(text string) string { return "\x1b[0m\x1b[2;3;4;36m" + text },
		Canvas.Color.Blue:    func(text string) string { return "\x1b[0m\x1b[2;3;4;34m" + text },
		Canvas.Color.Purple:  func(text string) string { return "\x1b[0m\x1b[2;3;4;38;5;93m" + text },
		Canvas.Color.Magenta: func(text string) string { return "\x1b[0m\x1b[2;3;4;35m" + text },
		Canvas.Color.Pink:    func(text string) string { return "\x1b[0m\x1b[2;3;4;38;5;205m" + text },
		Canvas.Color.Grey:    func(text string) string { return "\x1b[0m\x1b[2;3;4;38;5;240m" + text },
		Canvas.Color.White:   func(text string) string { return "\x1b[0m\x1b[2;3;4;37m" + text },
	},
	InvertItalicUline: t_ColorsAnsiFunc{
		Canvas.Color.Red:     func(text string) string { return "\x1b[0m\x1b[4;3;7;31m" + text },
		Canvas.Color.Orange:  func(text string) string { return "\x1b[0m\x1b[4;3;7;38;5;214m" + text },
		Canvas.Color.Yellow:  func(text string) string { return "\x1b[0m\x1b[4;3;7;33m" + text },
		Canvas.Color.Green:   func(text string) string { return "\x1b[0m\x1b[4;3;7;32m" + text },
		Canvas.Color.Cyan:    func(text string) string { return "\x1b[0m\x1b[4;3;7;36m" + text },
		Canvas.Color.Blue:    func(text string) string { return "\x1b[0m\x1b[4;3;7;34m" + text },
		Canvas.Color.Purple:  func(text string) string { return "\x1b[0m\x1b[4;3;7;38;5;93m" + text },
		Canvas.Color.Magenta: func(text string) string { return "\x1b[0m\x1b[4;3;7;35m" + text },
		Canvas.Color.Pink:    func(text string) string { return "\x1b[0m\x1b[4;3;7;38;5;205m" + text },
		Canvas.Color.Grey:    func(text string) string { return "\x1b[0m\x1b[4;3;7;38;5;240m" + text },
		Canvas.Color.White:   func(text string) string { return "\x1b[0m\x1b[4;3;7;37m" + text },
	},

	BoldDimInvertItalic: t_ColorsAnsiFunc{
		Canvas.Color.Red:     func(text string) string { return "\x1b[0m\x1b[1;2;3;7;31m" + text },
		Canvas.Color.Orange:  func(text string) string { return "\x1b[0m\x1b[1;2;3;7;38;5;214m" + text },
		Canvas.Color.Yellow:  func(text string) string { return "\x1b[0m\x1b[1;2;3;7;33m" + text },
		Canvas.Color.Green:   func(text string) string { return "\x1b[0m\x1b[1;2;3;7;32m" + text },
		Canvas.Color.Cyan:    func(text string) string { return "\x1b[0m\x1b[1;2;3;7;36m" + text },
		Canvas.Color.Blue:    func(text string) string { return "\x1b[0m\x1b[1;2;3;7;34m" + text },
		Canvas.Color.Purple:  func(text string) string { return "\x1b[0m\x1b[1;2;3;7;38;5;93m" + text },
		Canvas.Color.Magenta: func(text string) string { return "\x1b[0m\x1b[1;2;3;7;35m" + text },
		Canvas.Color.Pink:    func(text string) string { return "\x1b[0m\x1b[1;2;3;7;38;5;205m" + text },
		Canvas.Color.Grey:    func(text string) string { return "\x1b[0m\x1b[1;2;3;7;38;5;240m" + text },
		Canvas.Color.White:   func(text string) string { return "\x1b[0m\x1b[1;2;3;7;37m" + text },
	},
	BoldDimInvertUline: t_ColorsAnsiFunc{
		Canvas.Color.Red:     func(text string) string { return "\x1b[0m\x1b[1;2;4;7;31m" + text },
		Canvas.Color.Orange:  func(text string) string { return "\x1b[0m\x1b[1;2;4;7;38;5;214m" + text },
		Canvas.Color.Yellow:  func(text string) string { return "\x1b[0m\x1b[1;2;4;7;33m" + text },
		Canvas.Color.Green:   func(text string) string { return "\x1b[0m\x1b[1;2;4;7;32m" + text },
		Canvas.Color.Cyan:    func(text string) string { return "\x1b[0m\x1b[1;2;4;7;36m" + text },
		Canvas.Color.Blue:    func(text string) string { return "\x1b[0m\x1b[1;2;4;7;34m" + text },
		Canvas.Color.Purple:  func(text string) string { return "\x1b[0m\x1b[1;2;4;7;38;5;93m" + text },
		Canvas.Color.Magenta: func(text string) string { return "\x1b[0m\x1b[1;2;4;7;35m" + text },
		Canvas.Color.Pink:    func(text string) string { return "\x1b[0m\x1b[1;2;4;7;38;5;205m" + text },
		Canvas.Color.Grey:    func(text string) string { return "\x1b[0m\x1b[1;2;4;7;38;5;240m" + text },
		Canvas.Color.White:   func(text string) string { return "\x1b[0m\x1b[1;2;4;7;37m" + text },
	},
	BoldDimItalicUline: t_ColorsAnsiFunc{
		Canvas.Color.Red:     func(text string) string { return "\x1b[0m\x1b[1;2;3;4;31m" + text },
		Canvas.Color.Orange:  func(text string) string { return "\x1b[0m\x1b[1;2;3;4;38;5;214m" + text },
		Canvas.Color.Yellow:  func(text string) string { return "\x1b[0m\x1b[1;2;3;4;33m" + text },
		Canvas.Color.Green:   func(text string) string { return "\x1b[0m\x1b[1;2;3;4;32m" + text },
		Canvas.Color.Cyan:    func(text string) string { return "\x1b[0m\x1b[1;2;3;4;36m" + text },
		Canvas.Color.Blue:    func(text string) string { return "\x1b[0m\x1b[1;2;3;4;34m" + text },
		Canvas.Color.Purple:  func(text string) string { return "\x1b[0m\x1b[1;2;3;4;38;5;93m" + text },
		Canvas.Color.Magenta: func(text string) string { return "\x1b[0m\x1b[1;2;3;4;35m" + text },
		Canvas.Color.Pink:    func(text string) string { return "\x1b[0m\x1b[1;2;3;4;38;5;205m" + text },
		Canvas.Color.Grey:    func(text string) string { return "\x1b[0m\x1b[1;2;3;4;38;5;240m" + text },
		Canvas.Color.White:   func(text string) string { return "\x1b[0m\x1b[1;2;3;4;37m" + text },
	},
	BoldInvertItalicUline: t_ColorsAnsiFunc{
		Canvas.Color.Red:     func(text string) string { return "\x1b[0m\x1b[1;3;4;7;31m" + text },
		Canvas.Color.Orange:  func(text string) string { return "\x1b[0m\x1b[1;3;4;7;38;5;214m" + text },
		Canvas.Color.Yellow:  func(text string) string { return "\x1b[0m\x1b[1;3;4;7;33m" + text },
		Canvas.Color.Green:   func(text string) string { return "\x1b[0m\x1b[1;3;4;7;32m" + text },
		Canvas.Color.Cyan:    func(text string) string { return "\x1b[0m\x1b[1;3;4;7;36m" + text },
		Canvas.Color.Blue:    func(text string) string { return "\x1b[0m\x1b[1;3;4;7;34m" + text },
		Canvas.Color.Purple:  func(text string) string { return "\x1b[0m\x1b[1;3;4;7;38;5;93m" + text },
		Canvas.Color.Magenta: func(text string) string { return "\x1b[0m\x1b[1;3;4;7;35m" + text },
		Canvas.Color.Pink:    func(text string) string { return "\x1b[0m\x1b[1;3;4;7;38;5;205m" + text },
		Canvas.Color.Grey:    func(text string) string { return "\x1b[0m\x1b[1;3;4;7;38;5;240m" + text },
		Canvas.Color.White:   func(text string) string { return "\x1b[0m\x1b[1;3;4;7;37m" + text },
	},
	DimInvertItalicUline: t_ColorsAnsiFunc{
		Canvas.Color.Red:     func(text string) string { return "\x1b[0m\x1b[2;3;4;7;31m" + text },
		Canvas.Color.Orange:  func(text string) string { return "\x1b[0m\x1b[2;3;4;7;38;5;214m" + text },
		Canvas.Color.Yellow:  func(text string) string { return "\x1b[0m\x1b[2;3;4;7;33m" + text },
		Canvas.Color.Green:   func(text string) string { return "\x1b[0m\x1b[2;3;4;7;32m" + text },
		Canvas.Color.Cyan:    func(text string) string { return "\x1b[0m\x1b[2;3;4;7;36m" + text },
		Canvas.Color.Blue:    func(text string) string { return "\x1b[0m\x1b[2;3;4;7;34m" + text },
		Canvas.Color.Purple:  func(text string) string { return "\x1b[0m\x1b[2;3;4;7;38;5;93m" + text },
		Canvas.Color.Magenta: func(text string) string { return "\x1b[0m\x1b[2;3;4;7;35m" + text },
		Canvas.Color.Pink:    func(text string) string { return "\x1b[0m\x1b[2;3;4;7;38;5;205m" + text },
		Canvas.Color.Grey:    func(text string) string { return "\x1b[0m\x1b[2;3;4;7;38;5;240m" + text },
		Canvas.Color.White:   func(text string) string { return "\x1b[0m\x1b[2;3;4;7;37m" + text },
	},

	BoldDimInvertItalicUline: t_ColorsAnsiFunc{
		Canvas.Color.Red:     func(text string) string { return "\x1b[0m\x1b[1;2;3;4;7;31m" + text },
		Canvas.Color.Orange:  func(text string) string { return "\x1b[0m\x1b[1;2;3;4;7;38;5;214m" + text },
		Canvas.Color.Yellow:  func(text string) string { return "\x1b[0m\x1b[1;2;3;4;7;33m" + text },
		Canvas.Color.Green:   func(text string) string { return "\x1b[0m\x1b[1;2;3;4;7;32m" + text },
		Canvas.Color.Cyan:    func(text string) string { return "\x1b[0m\x1b[1;2;3;4;7;36m" + text },
		Canvas.Color.Blue:    func(text string) string { return "\x1b[0m\x1b[1;2;3;4;7;34m" + text },
		Canvas.Color.Purple:  func(text string) string { return "\x1b[0m\x1b[1;2;3;4;7;38;5;93m" + text },
		Canvas.Color.Magenta: func(text string) string { return "\x1b[0m\x1b[1;2;3;4;7;35m" + text },
		Canvas.Color.Pink:    func(text string) string { return "\x1b[0m\x1b[1;2;3;4;7;38;5;205m" + text },
		Canvas.Color.Grey:    func(text string) string { return "\x1b[0m\x1b[1;2;3;4;7;38;5;240m" + text },
		Canvas.Color.White:   func(text string) string { return "\x1b[0m\x1b[1;2;3;4;7;37m" + text },
	},
}

