name: Publish Release to Another Repo

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  cross-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout private submodule repository
        uses: actions/checkout@v5

      - name: Run build script
        run: |
          chmod +x ./scripts/build.sh
          ./scripts/build.sh

      - name: Prepare artifacts
        run: |
          mkdir -p artifacts
          cp -r ../bin/* artifacts/

      - name: Publish release in another repo
        uses: softprops/action-gh-release@v2
        with:
          repository: yshell-dev/xcss-core
          token: ${{ secrets.CROSS_REPO_TOKEN }}
          files: artifacts/**
        env:
          GITHUB_TOKEN: ${{ secrets.CROSS_REPO_TOKEN }}
