name: Release Binary

on:
  # push:
    # branches:
    #   - missions  # Fixed syntax
  workflow_dispatch:

permissions:
  contents: write

env:
  PACKAGE_REPO: "alchira/package"
  
jobs:
  bin-release:
    name: Build & Publish Binary
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v4 # Updated to v4

      - name: Get version from package
        id: pacver
        run: |
          version=$(< VERSION)
          echo "version=$version" >> $GITHUB_OUTPUT
          echo "patchTag=v$version" >> $GITHUB_OUTPUT
          echo "minorTag=v$(echo "$version" | cut -d '.' -f1-2)" >> $GITHUB_OUTPUT
          echo "majorTag=v$(echo "$version" | cut -d '.' -f1)" >> $GITHUB_OUTPUT
          # It's better to prefix tags with 'v' for standard release logic

      - name: Run build script
        run: |
          chmod +x ./scripts/build.sh
          ./scripts/build.sh

      - name: Prepare artifacts
        run: |
          mkdir -p dist
          cp -r ./binary/* dist/

      - name: Publish release (latest tag)
        uses: softprops/action-gh-release@v2
        with:
          repository: ${{ env.PACKAGE_REPO }}
          token: ${{ secrets.ALCHIRA_BINPUB }}
          tag_name: latest
          name: Release latest
          body_path: ./RELEASE.md
          files: dist/**
          overwrite_files: true

      - name: Publish release (Major Tag)
        uses: softprops/action-gh-release@v2
        with:
          repository: ${{ env.PACKAGE_REPO }}
          token: ${{ secrets.ALCHIRA_BINPUB }}
          tag_name: ${{ steps.pacver.outputs.majorTag }}
          name: Release ${{ steps.pacver.outputs.majorTag }}
          body_path: ./RELEASE.md
          files: dist/**
          overwrite_files: true

      - name: Publish release (Minor Tag)
        uses: softprops/action-gh-release@v2
        with:
          repository: ${{ env.PACKAGE_REPO }}
          token: ${{ secrets.ALCHIRA_BINPUB }}
          tag_name: ${{ steps.pacver.outputs.minorTag }}
          name: Release ${{ steps.pacver.outputs.minorTag }}
          body_path: ./RELEASE.md
          files: dist/**
          overwrite_files: true

      - name: Publish release (Patch Tag)
        uses: softprops/action-gh-release@v2
        with:
          repository: ${{ env.PACKAGE_REPO }}
          token: ${{ secrets.ALCHIRA_BINPUB }}
          tag_name: ${{ steps.pacver.outputs.patchTag }}
          name: Release ${{ steps.pacver.outputs.patchTag }}
          body_path: ./RELEASE.md
          files: dist/**
          overwrite_files: true
