name: Release Binary

on:
  push:
    branches: [main]
  repository_dispatch:
    types: [trigger-publish]
  workflow_dispatch:

permissions:
  contents: write

env:
  PACKAGE_REPO: yshelldev/xcss-package
  SCAFFOLD_REPO: yshelldev/xcss-scaffold

jobs:
  bin-release:
    name: Bin Update Trigger
    runs-on: ubuntu-latest
    if: (github.event_name == 'push' && github.ref == 'refs/heads/main' && contains(github.event.head_commit.message, '#Release')) || (github.event_name != 'push')

    steps:
      - name: Checkout current repo
        uses: actions/checkout@v3

      - name: Checkout xcss-package (read-only)
        uses: actions/checkout@v3
        with:
          repository: yshelldev/xcss-package
          token: ${{ secrets.XCSS_REPO_CROSS }}
          path: compiler

      - name: Get version from xcss-package
        id: pacver
        run: |
          cd compiler 
          version="v$(jq -r .compilerVersion package.json)"
          echo "version=$version" >> $GITHUB_OUTPUT

          patchTag=$version
          echo "patchTag=$patchTag" >> $GITHUB_OUTPUT

          minorTag=$(echo "$version" | cut -d '.' -f1-2)
          echo "minorTag=$minorTag" >> $GITHUB_OUTPUT

          majorTag=$(echo "$version" | cut -d '.' -f1)
          echo "majorTag=$majorTag" >> $GITHUB_OUTPUT

      - name: Run build script
        run: |
          chmod +x ./scripts/build.sh
          ./scripts/build.sh

      - name: Prepare artifacts
        run: |
          mkdir -p artifacts
          cp -r ./bin/* artifacts/

      - name: Publish release (Patch Tag)
        uses: softprops/action-gh-release@v2
        with:
          repository: ${{ env.PACKAGE_REPO }}
          token: ${{ secrets.XCSS_REPO_CROSS }}
          tag_name: ${{ steps.pacver.outputs.patchTag }}
          name: Release ${{ steps.pacver.outputs.patchTag }}
          body_path: ./RELEASE.md
          files: artifacts/**
          overwrite_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.XCSS_REPO_CROSS }}

      - name: Publish release (Minor Tag)
        uses: softprops/action-gh-release@v2
        with:
          repository: ${{ env.PACKAGE_REPO }}
          token: ${{ secrets.XCSS_REPO_CROSS }}
          tag_name: ${{ steps.pacver.outputs.minorTag }}
          name: Release ${{ steps.pacver.outputs.minorTag }}
          body_path: ./RELEASE.md
          files: artifacts/**
          overwrite_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.XCSS_REPO_CROSS }}

      - name: Publish release (Major Tag)
        uses: softprops/action-gh-release@v2
        with:
          repository: ${{ env.PACKAGE_REPO }}
          token: ${{ secrets.XCSS_REPO_CROSS }}
          tag_name: ${{ steps.pacver.outputs.majorTag }}
          name: Release ${{ steps.pacver.outputs.majorTag }}
          body_path: ./RELEASE.md
          files: artifacts/**
          overwrite_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.XCSS_REPO_CROSS }}

      - name: Publish release (latest tag)
        uses: softprops/action-gh-release@v2
        with:
          repository: ${{ env.PACKAGE_REPO }}
          token: ${{ secrets.XCSS_REPO_CROSS }}
          tag_name: latest
          name: Release latest
          body_path: ./RELEASE.md
          files: artifacts/**
          overwrite_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.XCSS_REPO_CROSS }}

  publish-package:
    name: Trigger Package Release
    runs-on: ubuntu-latest
    needs: bin-release

    steps:
      - name: Checkout ${{ env.PACKAGE_REPO }} (read-only)
        uses: actions/checkout@v4
        with:
          repository: ${{ env.PACKAGE_REPO }}
          token: ${{ secrets.XCSS_REPO_CROSS }}
          lfs: false

      - name: Sync and push submodule updates for scaffold
        run: |
          git submodule update --init ./scaffold
          node execute
          
          cd scaffold
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.XCSS_REPO_CROSS }}@github.com/yshelldev/xcss-scaffold.git
          git fetch origin main

          if [[ $(git status --porcelain) ]]; then
            git add .
            git commit -m "Version Update"
            git pull --rebase origin main
            git push origin main
          else
            echo "Repository is already up-to-date."
          fi

          cd ..
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.XCSS_REPO_CROSS }}@github.com/yshelldev/xcss-package.git
          git fetch origin main
          
          if [[ $(git status --porcelain) ]]; then
            git add .
            git commit -m "Version Update"
            git pull --rebase origin main
            git push origin main
          else
            echo "Repository is already up-to-date."
          fi

      - name: Trigger publish workflow on Parent Repo
        uses: peter-evans/repository-dispatch@v2
        with:
          repository: ${{ env.PACKAGE_REPO }}
          token: ${{ secrets.XCSS_REPO_CROSS }}
          event-type: trigger-publish

  publish-scaffold:
    name: Trigger Scaffold Release
    runs-on: ubuntu-latest
    needs: publish-package

    steps:
      - name: Checkout ${{ env.SCAFFOLD_REPO }} (read-only)
        uses: actions/checkout@v3
        with:
          repository: ${{ env.SCAFFOLD_REPO }}
          token: ${{ secrets.XCSS_REPO_CROSS }}

      - name: Trigger publish workflow on Parent Repo
        uses: peter-evans/repository-dispatch@v2
        with:
          repository: ${{ env.SCAFFOLD_REPO }}
          token: ${{ secrets.XCSS_REPO_CROSS }}
          event-type: trigger-publish
